import mongoose from "mongoose";

const friendRequestSchema = new mongoose.Schema({
    sender: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "User",
        required: true
    },
    recipient: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "User",
        required: true
    },
    status: {
        type: String,
        enum: ["pending", "accepted"],
        default: "pending"
    }
}, {
    timestamps: true
})

const FriendRequest = mongoose.model("FriendRequest", friendRequestSchema);

export default FriendRequest;

// Example :-
// {
//   "_id": "abc123", //generated by MongoDB and it is useful to identify the request
//   "sender": "kevalId",
//   "recipient": "joeId"
// }
